### ISSUE TITLE
Optionally generate npm-shrinkwrap

### ISSUE THREAD

**Issue by mstuart** [nodesecurity/grunt-nsp-shrinkwrap#5]
I've noticed npm-shrinkwrap is particularly difficult to use in large teams (30+ people actively contributing to 1 repo).  I'd like to add an option for projects that don't use npm-shrinkwrap.json.  

`shrinkwrap` always defaults to true, but if you want to mark it false you can add this to your Gruntfile:
```javascript
'validate-shrinkwrap': {
   options: {
      shrinkwrap: false
   }
}
```

`shrinkwrap: false` will generate npm-shrinkwrap.json, run the task as normal, and then remove npm-shrinkwrap.json

**Comment by evilpacket** [comment]
Migrate to grunt-requiresafe for all your package.json and shrinkwrap validation needs. Best part. it's not ghetto slow anymore. Feedback welcome. :)
